version: "3.6"

services:
  pi:
    image: sixeyed/pi:${TAG:-2002}
    build:
      context: .
      cache_from:
        - sixeyed/pi:${TAG:-2002}
      args:
        BUILDKIT_INLINE_CACHE: 1
