version: "3.7"

services:
  gogs:
    image: sixeyed/gogs:bday7
    ports:
      - "3000:3000"
    networks:
      - infrastructure

  jenkins:
    image: sixeyed/jenkins:bday7
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infrastructure

networks:
  infrastructure:
    name: build-infrastructure
