apiVersion: v1
kind: ServiceAccount
metadata:
  name: pi-sa
  namespace: pi
  labels:
    app: pi-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: pi-proxy
  namespace: pi-public
  labels:
    app: pi-proxy
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: pi-proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-proxy
  namespace: pi
  labels:
    app: pi-proxy
    version: "2002"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-proxy
      version: "2002"
  template:
    metadata:
      labels:
        app: pi-proxy
        version: "2002"
    spec:
      serviceAccountName: pi-sa
      containers:
        - image: nginx:1.17.8-alpine
          name: nginx
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: pi-nginx-configmap
