apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-account
  namespace: pi
  labels:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: pi-web
  namespace: pi
  labels:
    app: web
spec:
  ports:
    - port: 8031
      targetPort: 80
      name: http
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pi-web-internal
  namespace: pi
  labels:
    app: web
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: pi
  labels:
    app: web
    version: "2002"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: "2002"
  template:
    metadata:
      labels:
        app: web
        version: "2002"
    spec:
      serviceAccountName: web-service-account
      containers:
        - image: sixeyed/pi:2002
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: web-configmap
