name: Build with buildx

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build and push image
        run: |
          docker login -u $USER -p $TOKEN          
          docker buildx build \
            -t $TAG \
            --cache-from=type=registry,ref=$CACHE_TAG \
            --cache-to=type=registry,ref=$CACHE_TAG,mode=max \
            --push \
            .
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          TAG: sixeyed/pi:2002-ci-buildx
          CACHE_TAG: sixeyed/pi:2002-ci-buildx-cache
