name: Check versions

on:
  push:
    paths:
      - "src/**"

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: Update Compose
        id: compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Check tool versions
        run: |
          docker version
          docker-compose version
