name: Build with buildx

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Docker 19.03 with buildx
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 19.03
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
