name: Check versions

on:
  push:
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest 
      -
        name: Check tool versions
        run: |
          docker version
          docker-compose version
          docker buildx version
